os: linux

language: go

go: 
    - "1.10"

before_install:
    - go get github.com/tcnksm/ghr

after_install:
    - go build
    - tar -cvzf adz-$(cat .buildno).tar.gz dist/*
    - ghr  --username postfix-tools --token $GITHUB_TOKEN --replace $(cat .buildno) adz-$(cat .buildno).tar.gz
